name: cschool_webapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flamingo:
  flamingo_annotation:
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  get: ^3.24.0
  supercharged: ^1.12.0
  styled_widget: ^0.2.2
  logger: ^0.9.4
  csv: ^4.1.0
  after_layout: ^1.0.7+2
  fuzzy: ^0.3.0
  uuid: 2.2.2
  path_provider: ^1.6.27
  form_field_validator: ^1.0.1
  flutter_beautiful_popup: ^1.5.0
  modal_progress_hud: ^0.1.3
  audioplayers: ^0.17.3
  flutter_cache_manager: ^2.1.1
  enum_to_string: ^1.0.1
  horizontal_data_table: ^2.2.0
  cached_network_image: ^2.5.0
  file_picker: ^2.1.6
  archive: ^2.0.13

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dependency_overrides:
  intl: 0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flamingo_generator:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/login/

  fonts:
    - family:  CSchool
      fonts:
        - asset: assets/fonts/CSchool.ttf