/// Flutter icons CSchool
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CSchool
///      fonts:
///       - asset: fonts/CSchool.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

// Flutter imports:
import 'package:flutter/widgets.dart';

class CSchool {
  CSchool._();

  static const _kFontFam = 'CSchool';
  static const String? _kFontPkg = null;

  static const IconData volume = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData study = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData word_card = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData books_stack_of_three = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrong_box = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData male = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData female = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData correct = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrong = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xf004, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_slash = IconData(0xf070, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData envelope = IconData(0xf0e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microphone = IconData(0xf130, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock_alt = IconData(0xf13e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData google = IconData(0xf1a0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user_circle = IconData(0xf2bd, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_f = IconData(0xf39e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_dots = IconData(0xf4ad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
